services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_PASSWORD=admin123
      - DATABASE_USERNAME=postgres
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi

      - SECRET_KEY=3ca0e6108585d3625c64245bc4d6db4412c416dbfae615c450957c24cf546cf2
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./:/app
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  postgres:
    image: postgres:18.4
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
  